### ISSUE TITLE
bug with duplicate inputs

### ISSUE THREAD

**Issue by ventrebleu** [ten1seven/infieldLabel#5]
Hello and thanks for this awesome plugin!

I'm testing it and it works great so far... until my problem.

I have two forms on my page with some inputs with the same name but I'm not displaying them at the same time.
Trouble is, the second input with the same name won't work: it will fire the first occurrence.
I have tried to look into your code but I have no luck so far.

If you have a lead, I would much appreciate it.

**Comment by ten1seven** [comment]
Hi @ventrebleu, I feel terrible for not seeing this issue you reported. Were you able to resolve this some other way? Is there anything I can do at this point to help?
