### ISSUE TITLE
Issue with textarea

### ISSUE THREAD

**Issue by adsim** [ten1seven/infieldLabel#9]
First of all: I love your plugin. It works great and is simple to use. Thanks a lot.
But it seems not to work with textareas as it puts the placeholder-hide class on init on the textarea and that's it.
What's wrong?

**Comment by ten1seven** [comment]
Hi @adsim, glad you like the plugin!

It turns out I wasn't forward-thinking enough to add support for textareas (just inputs) 😞 

I can add that but it'll be a day or two. Hope that doesn't hold you up.

**Comment by adsim** [comment]
Hi @ten1seven, are there any news about this topic?

**Comment by ten1seven** [comment]
Hi @adsim, sorry! This remains on my radar but I've been buried in project work that's wrapping up this week so I should have time to address this very soon.

**Comment by ten1seven** [comment]
Hi @adsim, I just published version 1.1.0 with support for textareas. Check it out and let me know if you run into any issues.

**Comment by adsim** [comment]
Hi @ten1seven, thanks a lot. Works great.

**Comment by ten1seven** [comment]
Great!
